version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "alpine/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "dev-tools/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "mariadb-lite/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "mu-plugins/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "nginx/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "php-fpm/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "skeleton/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "statsd/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "traefik/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "wordpress/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "wp-test-base/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "wp-test-runner/"
    schedule:
      interval: "weekly"


