FROM alpine:edge

RUN \
    echo https://dl-cdn.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories && \
    echo "@317m https://dl-cdn.alpinelinux.org/alpine/v3.17/main" >> /etc/apk/repositories && \
    apk add --no-cache ca-certificates curl tar xz openssl less bash mysql-client@317m mariadb-common@317m su-exec shadow git jq icu-data-full ghostscript msmtp php8 php8-fpm php8-pear \
        php8-pecl-apcu \
        php8-bcmath \
        php8-calendar \
        php8-ctype \
        php8-curl \
        php8-dom \
        php8-exif \
        php8-fileinfo \
        php8-ftp \
        php8-gd \
        php8-pecl-gmagick \
        php8-gmp \
        php8-iconv \
        php8-intl \
        php8-json \
        php8-mbstring \
        php8-pecl-igbinary \
        php8-pecl-mcrypt \
        php8-pecl-memcache \
        php8-pecl-memcached \
        php8-mysqli \
        php8-mysqlnd \
        php8-opcache \
        php8-openssl \
        php8-pcntl \
        php8-pdo \
        php8-pdo_sqlite \
        php8-phar \
        php8-posix \
        php8-session \
        php8-shmop \
        php8-simplexml \
        php8-soap \
        php8-sockets \
        php8-sodium \
        php8-sqlite3 \
        php8-pecl-ssh2 \
        php8-sysvsem \
        php8-sysvshm \
        php8-pecl-timezonedb \
        php8-tokenizer \
        php8-pecl-xdebug \
        php8-xml \
        php8-xmlreader \
        php8-xmlwriter \
        php8-zip

RUN \
    [ ! -f /usr/sbin/php-fpm ] && ln -s /usr/sbin/php-fpm8 /usr/sbin/php-fpm; \
    [ ! -f /usr/bin/php ] && ln -s /usr/bin/php8 /usr/bin/php; \
    [ ! -f /usr/bin/pecl ] && ln -s /usr/bin/pecl8 /usr/bin/pecl; \
    [ ! -f /usr/bin/pear ] && ln -s /usr/bin/pear8 /usr/bin/pear; \
    [ ! -f /usr/bin/peardev ] && ln -s /usr/bin/peardev8 /usr/bin/peardev; \
    [ ! -f /usr/bin/phar ] && ln -s /usr/bin/phar8 /usr/bin/phar; \
    [ ! -f /usr/bin/phar.phar ] && ln -s /usr/bin/phar8 /usr/bin/phar.phar

RUN \
    pecl update-channels && \
    rm -rf /tmp/pear ~/.pearrc

RUN adduser -u 82 -D -S -G www-data www-data
RUN install -d -m 0777 -o www-data -g www-data /var/www/html

RUN \
    wget -O /usr/local/bin/phpunit https://phar.phpunit.de/phpunit-9.phar && chmod 0755 /usr/local/bin/phpunit && \
    wget -O /usr/local/bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod 0755 /usr/local/bin/wp && \
    wget -q https://getcomposer.org/installer -O - | php -- --install-dir=/usr/bin/ --filename=composer

ENV WP_CLI_CONFIG_PATH /config/wp-cli.yaml
ENV PHP_INI_DIR /etc/php8

COPY rootfs-common/ /
COPY rootfs80/ /

WORKDIR /var/www/html
STOPSIGNAL SIGQUIT
EXPOSE 9000
ENTRYPOINT ["docker-php-entrypoint"]
CMD ["run.sh"]
