FROM ghcr.io/automattic/vip-container-images/php-helpers:latest@sha256:7ee54e4e0007a61f7c48499aa8dd595043a7624e51c78f2aac202927684fdd4f AS build
FROM ubuntu:24.04@sha256:728785b59223d755e3e5c5af178fab1be7031f3522c5ccd7a0b32b80d8248123
ARG TARGETARCH

# We lack: newrelic
RUN \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get -q update && \
    apt-get -y install eatmydata && \
    mkdir -p /usr/lib/libeatmydata && ln -s -t /usr/lib/libeatmydata/ /usr/lib/$(uname -m)-linux-gnu/libeatmydata.so* && \
    export LD_PRELOAD=/usr/lib/libeatmydata/libeatmydata.so && \
    apt-get -y upgrade && \
    apt-get install -y curl lsb-release ca-certificates gnupg --no-install-recommends && \
    echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list && \
    curl -sSL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x71DAEAAB4AD4CAB6" | gpg --dearmor > /etc/apt/trusted.gpg.d/ppa-ondrej-php.gpg && \
    apt-get -q update && \
    apt-get install -y --no-install-recommends \
        ghostscript git jq less libatomic1 libglib2.0-0 libmysqlclient21 libpcre3 msmtp mysql-client \
        nano openssl vim wget zstd && \
    # apt-get install -y --no-install-recommends \
    #     php8.5-apcu php8.5-bcmath php8.5-cli php8.5-curl php8.5-fpm php8.5-gd php8.5-gmagick php8.5-gmp php8.5-gnupg \
    #     php8.5-igbinary php8.5-intl php8.5-mbstring php8.5-mcrypt php8.5-memcache php8.5-memcached php8.5-mysql \
    #     php8.5-soap php8.5-sqlite3 php8.5-ssh2 php8.5-xdebug php8.5-xml php8.5-zip && \
    apt-get install -y --no-install-recommends \
        php8.5-bcmath php8.5-cli php8.5-curl php8.5-fpm php8.5-gd php8.5-gmp \
        php8.5-intl php8.5-mbstring php8.5-mysql \
        php8.5-soap php8.5-sqlite3 php8.5-xml php8.5-zip && \
    phpdismod ffi gettext readline sysvmsg xsl xdebug && \
    apt-get autoremove --purge -y && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/* && \
    ln -s /usr/sbin/php-fpm8.5 /usr/sbin/php-fpm && \
    \
    deluser --remove-home --quiet ubuntu && \
    usermod -d /home/www-data -s /bin/bash www-data && \
    install -d -D -m 0750 -o www-data -g www-data /home/www-data && \
    install -d -D -m 0777 -o www-data -g www-data /var/www/html && \
    install -d -D -m 0755 -o www-data -g www-data /run/php && \
    install -d -D -m 0755 -o root -g root /usr/local/share && \
    \
    wget -qO /usr/local/bin/wp.phar https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
        php -r '(new Phar("/usr/local/bin/wp.phar"))->extractTo("/usr/local/share/wp");' && \
        mv /usr/local/bin/wp.phar /usr/local/bin/wp && \
        chmod 0755 /usr/local/bin/wp && \
    wget https://getcomposer.org/installer -qO - | php -- --install-dir=/usr/bin/ --filename=composer

ENV WP_CLI_CONFIG_PATH=/config/wp-cli.yaml

ADD --chmod=0755 https://github.com/Automattic/cron-control-runner/releases/download/1.1.0/cron-control-runner-linux-${TARGETARCH} /usr/bin/cron-control-runner
COPY --from=build /usr/lib/php/20240924/timezonedb.so /usr/lib/php/20240924/
COPY --from=build /mydumper /myloader /usr/local/bin/
COPY --from=build /mydumper.cnf /etc/
COPY rootfs/ /
COPY rootfs-php/ /etc/php/8.5/

RUN phpenmod timezonedb

WORKDIR /var/www/html
STOPSIGNAL SIGQUIT
EXPOSE 9000
ENTRYPOINT ["docker-php-entrypoint"]
CMD ["run.sh"]
