FROM ubuntu:22.04 AS build
RUN \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get -q update && \
    apt-get -y install eatmydata && \
    eatmydata apt-get install -y software-properties-common gnupg --no-install-recommends && \
    eatmydata add-apt-repository -y ppa:ondrej/php && \
    eatmydata apt-get install -y php7.4-dev php7.4-xml && \
    eatmydata apt-get install -y php-pear --no-install-recommends && \
    pecl install timezonedb

FROM ubuntu:22.04

# Extra PHP extensions: msgpack (because of memcache)
# We lack: newrelic
RUN \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get -q update && \
    apt-get -y install eatmydata && \
    eatmydata apt-get install -y software-properties-common gnupg --no-install-recommends && \
    eatmydata add-apt-repository -y ppa:ondrej/php && \
    eatmydata apt-get install -y curl less git jq mysql-client openssl wget cron && \
    eatmydata apt-get install -y ghostscript msmtp --no-install-recommends && \
    eatmydata apt-get install -y \
        php7.4-cli php7.4-fpm \
        php7.4-apcu php7.4-bcmath php7.4-curl php7.4-gd php7.4-gmagick php7.4-gmp php7.4-gnupg php7.4-intl php7.4-igbinary php7.4-mbstring php7.4-mcrypt \
        php7.4-memcache php7.4-memcached php7.4-mysql php7.4-soap php7.4-sqlite3 php7.4-ssh2 php7.4-xdebug php7.4-xml php7.4-zip && \
    eatmydata apt-get install -y php-pear --no-install-recommends && \
    phpdismod ffi gettext readline sysvmsg xsl xdebug && \
    eatmydata apt-get remove --purge -y software-properties-common && \
    rm -rf /var/lib/apt/lists/* && \
    eatmydata apt-get autoremove --purge -y && \
    ln -s /usr/sbin/php-fpm7.4 /usr/sbin/php-fpm

RUN \
    usermod -d /home/www-data -s /bin/bash www-data && \
    install -d -D -m 0750 -o www-data -g www-data /home/www-data && \
    install -d -D -m 0777 -o www-data -g www-data /var/www/html && \
    install -d -D -m 0755 -o www-data -g www-data /run/php

RUN \
    wget -O /usr/local/bin/phpunit https://phar.phpunit.de/phpunit-9.phar && chmod 0755 /usr/local/bin/phpunit && \
    wget -O /usr/local/bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod 0755 /usr/local/bin/wp && \
    wget -q https://getcomposer.org/installer -O - | php -- --install-dir=/usr/bin/ --filename=composer

ENV WP_CLI_CONFIG_PATH /config/wp-cli.yaml

COPY --from=build /usr/lib/php/20190902/timezonedb.so /usr/lib/php/20190902/timezonedb.so
COPY rootfs/ /
COPY rootfs-php/ /etc/php/7.4/

RUN phpenmod timezonedb

WORKDIR /var/www/html
STOPSIGNAL SIGQUIT
EXPOSE 9000
ENTRYPOINT ["docker-php-entrypoint"]
CMD ["run.sh"]
