FROM ghcr.io/automattic/vip-container-images/php-helpers:latest@sha256:75c54e169c06e44fe4214e810c7cbb53caa9f71c8a6ce031da7193f402fbd8a2 AS build
FROM ubuntu:24.04@sha256:72297848456d5d37d1262630108ab308d3e9ec7ed1c3286a32fe09856619a782

# Extra PHP extensions: msgpack (because of memcache)
# We lack: newrelic
RUN \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get -q update && \
    apt-get -y install eatmydata && \
    mkdir -p /usr/lib/libeatmydata && ln -s -t /usr/lib/libeatmydata/ /usr/lib/$(uname -m)-linux-gnu/libeatmydata.so* && \
    eatmydata apt-get -y upgrade && \
    eatmydata apt-get install -y curl lsb-release ca-certificates gnupg --no-install-recommends && \
    echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list && \
    curl -sSL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x71DAEAAB4AD4CAB6" | gpg --dearmor > /etc/apt/trusted.gpg.d/ppa-ondrej-php.gpg && \
    eatmydata apt-get -q update && \
    eatmydata apt-get install -y --no-install-recommends \
        ghostscript git jq less libatomic1 libglib2.0-0 libmysqlclient21 libpcre3 msmtp mysql-client \
        nano openssl vim wget zstd && \
    eatmydata apt-get install -y --no-install-recommends \
        php8.2-apcu php8.2-bcmath php8.2-cli php8.2-curl php8.2-fpm php8.2-gd php8.2-gmagick php8.2-gmp php8.2-gnupg \
        php8.2-igbinary php8.2-intl php8.2-mbstring php8.2-mcrypt php8.2-memcache php8.2-memcached php8.2-mysql \
        php8.2-soap php8.2-sqlite3 php8.2-ssh2 php8.2-xdebug php8.2-xml php8.2-zip && \
    phpdismod ffi gettext readline sysvmsg xsl xdebug && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/* && \
    eatmydata apt-get autoremove --purge -y && \
    ln -s /usr/sbin/php-fpm8.2 /usr/sbin/php-fpm && \
    \
    deluser --remove-home --quiet ubuntu && \
    usermod -d /home/www-data -s /bin/bash www-data && \
    install -d -D -m 0750 -o www-data -g www-data /home/www-data && \
    install -d -D -m 0777 -o www-data -g www-data /var/www/html && \
    install -d -D -m 0755 -o www-data -g www-data /run/php && \
    install -d -D -m 0755 -o root -g root /usr/local/share && \
    \
    wget -qO /usr/local/bin/wp.phar https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
        php -r '(new Phar("/usr/local/bin/wp.phar"))->extractTo("/usr/local/share/wp");' && \
        mv /usr/local/bin/wp.phar /usr/local/bin/wp && \
        chmod 0755 /usr/local/bin/wp && \
    wget https://getcomposer.org/installer -qO - | php -- --install-dir=/usr/bin/ --filename=composer

ENV WP_CLI_CONFIG_PATH=/config/wp-cli.yaml

RUN \
    ARCH="$(arch)"; \
    LATEST=$(curl -w '%{url_effective}' -ILsS https://github.com/Automattic/cron-control-runner/releases/latest -o /dev/null | sed -e 's|^.*/||'); \
    if [ "${ARCH}" = "arm64" ] || [ "${ARCH}" = "aarch64" ]; then \
        ARCH="arm64"; \
    elif [ "${ARCH}" = "x86_64" ] || [ "${ARCH}" = "amd64" ]; then \
        ARCH="amd64"; \
    else \
        echo "(!) Unsupported architecture: ${ARCH}"; \
        exit 1; \
    fi && \
    curl "https://github.com/Automattic/cron-control-runner/releases/download/${LATEST}/cron-control-runner-linux-${ARCH}" -SLo /usr/bin/cron-control-runner && \
    chmod +x /usr/bin/cron-control-runner

COPY --from=build /usr/lib/php/20220829/timezonedb.so /usr/lib/php/20220829/timezonedb.so
COPY --from=build /mydumper /myloader /usr/local/bin/
COPY --from=build /mydumper.cnf /etc/
COPY rootfs/ /
COPY rootfs-php/ /etc/php/8.2/

RUN phpenmod timezonedb

WORKDIR /var/www/html
STOPSIGNAL SIGQUIT
EXPOSE 9000
ENTRYPOINT ["docker-php-entrypoint"]
CMD ["run.sh"]
