FROM ghcr.io/automattic/vip-container-images/php-helpers:latest@sha256:5240ace0386e93c8a9a52dbfa208c3590fd0c7d599ca93b555c80a3078681caa AS build
FROM debian:bookworm@sha256:8a8cd02c5912770b4980228a54d4aff9e4f986f1eb2525d2d371dec5232cefcc
ARG TARGETARCH

# We lack: newrelic
RUN \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get -q update && \
    apt-get -y install eatmydata && \
    mkdir -p /usr/lib/libeatmydata && ln -s -t /usr/lib/libeatmydata/ /usr/lib/$(uname -m)-linux-gnu/libeatmydata.so* && \
    export LD_PRELOAD=/usr/lib/libeatmydata/libeatmydata.so && \
    apt-get -y upgrade && \
    apt-get install -y curl lsb-release ca-certificates gnupg --no-install-recommends && \
    curl -SLo /tmp/debsuryorg-archive-keyring.deb https://packages.sury.org/debsuryorg-archive-keyring.deb && \
    echo '7511384559c9ddf1d5ce5f60be429ae9d4e7d01d9480d6f1b7a30c0810cf8b60  /tmp/debsuryorg-archive-keyring.deb' | sha256sum -c - && \
    dpkg -i /tmp/debsuryorg-archive-keyring.deb && \
    rm -f /tmp/debsuryorg-archive-keyring.deb && \
    CODENAME="$(lsb_release -sc)" && \
    echo "deb [signed-by=/usr/share/keyrings/debsuryorg-archive-keyring.gpg] https://packages.sury.org/php/ ${CODENAME} main" > /etc/apt/sources.list.d/php.list && \
    apt-get -q update && \
    apt-get install -y --no-install-recommends \
        ghostscript git jq less libatomic1 libglib2.0-0 libmariadb3 libpcre3 msmtp mariadb-client \
        nano openssl vim wget zstd && \
    apt-get install -y --no-install-recommends libmemcached11 && \
    apt-get install -y --no-install-recommends \
        php8.5-apcu php8.5-bcmath php8.5-cli php8.5-curl php8.5-fpm php8.5-gd php8.5-gmagick php8.5-gmp php8.5-gnupg \
        php8.5-igbinary php8.5-intl php8.5-mbstring php8.5-mcrypt php8.5-memcached php8.5-mysql \
        php8.5-soap php8.5-sqlite3 php8.5-ssh2 php8.5-xdebug php8.5-xml php8.5-zip && \
    echo 'extension=memcache.so' > /etc/php/8.5/mods-available/memcache.ini && \
    \
    phpdismod ffi gettext readline sysvmsg xsl xdebug && \
    apt-get autoremove --purge -y && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/* && \
    ln -s /usr/sbin/php-fpm8.5 /usr/sbin/php-fpm && \
    \
    usermod -d /home/www-data -s /bin/bash www-data && \
    install -d -D -m 0750 -o www-data -g www-data /home/www-data && \
    install -d -D -m 0777 -o www-data -g www-data /var/www/html && \
    install -d -D -m 0755 -o www-data -g www-data /run/php && \
    install -d -D -m 0755 -o root -g root /usr/local/share && \
    \
    wget -qO /usr/local/bin/wp.phar https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
        php -r '(new Phar("/usr/local/bin/wp.phar"))->extractTo("/usr/local/share/wp");' && \
        mv /usr/local/bin/wp.phar /usr/local/bin/wp && \
        chmod 0755 /usr/local/bin/wp && \
    wget https://getcomposer.org/installer -qO - | php -- --install-dir=/usr/bin/ --filename=composer

ENV WP_CLI_CONFIG_PATH=/config/wp-cli.yaml

ADD --chmod=0755 https://github.com/Automattic/cron-control-runner/releases/download/1.1.0/cron-control-runner-linux-${TARGETARCH} /usr/bin/cron-control-runner
COPY --from=build /usr/lib/php/20250925/memcache.so /usr/lib/php/20250925/timezonedb.so /usr/lib/php/20250925/
COPY --from=build /mydumper /myloader /usr/local/bin/
COPY --from=build /mydumper.cnf /etc/
COPY rootfs/ /
COPY rootfs-php/ /etc/php/8.5/

RUN phpenmod memcache memcached gmagick timezonedb

WORKDIR /var/www/html
STOPSIGNAL SIGQUIT
EXPOSE 9000
ENTRYPOINT ["docker-php-entrypoint"]
CMD ["run.sh"]
