FROM ghcr.io/automattic/vip-container-images/php-helpers:latest@sha256:1eb0ea800272724aa9e2b7b3386db18615553af7ee252ecaaec9979863be916d AS build
FROM ubuntu:24.04@sha256:1e622c5f073b4f6bfad6632f2616c7f59ef256e96fe78bf6a595d1dc4376ac02
ARG TARGETARCH

# We lack: newrelic
RUN \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get -q update && \
    apt-get -y install eatmydata && \
    mkdir -p /usr/lib/libeatmydata && ln -s -t /usr/lib/libeatmydata/ /usr/lib/$(uname -m)-linux-gnu/libeatmydata.so* && \
    export LD_PRELOAD=/usr/lib/libeatmydata/libeatmydata.so && \
    apt-get -y upgrade && \
    apt-get install -y curl lsb-release ca-certificates gnupg --no-install-recommends && \
    echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list && \
    curl -sSL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x71DAEAAB4AD4CAB6" | gpg --dearmor > /etc/apt/trusted.gpg.d/ppa-ondrej-php.gpg && \
    apt-get -q update && \
    apt-get install -y --no-install-recommends \
        ghostscript git jq less libatomic1 libglib2.0-0 libmysqlclient21 libpcre3 msmtp mysql-client \
        nano openssl vim wget zstd && \
    apt-get install -y --no-install-recommends \
        php8.4-apcu php8.4-bcmath php8.4-cli php8.4-curl php8.4-fpm php8.4-gd php8.4-gmagick php8.4-gmp php8.4-gnupg \
        php8.4-igbinary php8.4-intl php8.4-mbstring php8.4-mcrypt php8.4-memcache php8.4-memcached php8.4-mysql \
        php8.4-soap php8.4-sqlite3 php8.4-ssh2 php8.4-xdebug php8.4-xml php8.4-zip && \
    phpdismod ffi gettext readline sysvmsg xsl xdebug && \
    apt-get autoremove --purge -y && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/* && \
    ln -s /usr/sbin/php-fpm8.4 /usr/sbin/php-fpm && \
    \
    deluser --remove-home --quiet ubuntu && \
    usermod -d /home/www-data -s /bin/bash www-data && \
    install -d -D -m 0750 -o www-data -g www-data /home/www-data && \
    install -d -D -m 0777 -o www-data -g www-data /var/www/html && \
    install -d -D -m 0755 -o www-data -g www-data /run/php && \
    install -d -D -m 0755 -o root -g root /usr/local/share && \
    \
    wget -qO /usr/local/bin/wp.phar https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
        php -r '(new Phar("/usr/local/bin/wp.phar"))->extractTo("/usr/local/share/wp");' && \
        mv /usr/local/bin/wp.phar /usr/local/bin/wp && \
        chmod 0755 /usr/local/bin/wp && \
    wget https://getcomposer.org/installer -qO - | php -- --install-dir=/usr/bin/ --filename=composer

ENV WP_CLI_CONFIG_PATH=/config/wp-cli.yaml

ADD --chmod=0755 https://github.com/Automattic/cron-control-runner/releases/download/1.0.0/cron-control-runner-linux-${TARGETARCH} /usr/bin/cron-control-runner
COPY --from=build /usr/lib/php/20240924/timezonedb.so /usr/lib/php/20240924/
COPY --from=build /mydumper /myloader /usr/local/bin/
COPY --from=build /mydumper.cnf /etc/
COPY rootfs/ /
COPY rootfs-php/ /etc/php/8.4/

RUN phpenmod timezonedb

WORKDIR /var/www/html
STOPSIGNAL SIGQUIT
EXPOSE 9000
ENTRYPOINT ["docker-php-entrypoint"]
CMD ["run.sh"]
