FROM alpine:edge as build
RUN apk add --no-cache php82-dev gcc make php82-pear php82-openssl libc-dev graphicsmagick-dev libtool
RUN pecl82 channel-update pecl.php.net
RUN pecl82 install memcache < /dev/null
RUN pecl82 install channel://pecl.php.net/gmagick-2.0.6RC1 < /dev/null

FROM alpine:edge

RUN echo https://dl-cdn.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories
RUN \
    apk add --no-cache ca-certificates curl tar xz openssl less bash mariadb-client su-exec shadow git jq icu-data-full php82 php82-fpm php82-pear \
        graphicsmagick libgomp \
        php82-pecl-apcu \
        php82-bcmath \
        php82-calendar \
        php82-ctype \
        php82-curl \
        php82-dom \
        php82-exif \
        php82-fileinfo \
        php82-ftp \
        php82-gd \
        # php82-pecl-gmagick \
        php82-gmp \
        php82-iconv \
        php82-intl \
        # php82-json \
        php82-mbstring \
        # php82-pecl-mcrypt \
        # php82-pecl-memcache \
        # php82-pecl-memcached \
        php82-mysqli \
        php82-mysqlnd \
        php82-opcache \
        php82-openssl \
        php82-pcntl \
        php82-pdo \
        php82-pdo_sqlite \
        php82-phar \
        php82-posix \
        php82-session \
        php82-shmop \
        php82-simplexml \
        php82-soap \
        php82-sockets \
        php82-sodium \
        php82-sqlite3 \
        # php82-pecl-ssh2 \
        php82-sysvsem \
        php82-sysvshm \
        php82-pecl-timezonedb \
        php82-tokenizer \
        php82-pecl-xdebug \
        php82-xml \
        php82-xmlreader \
        php82-xmlwriter \
        php82-zip

RUN ln -s /usr/sbin/php-fpm82 /usr/sbin/php-fpm
RUN ln -s /usr/bin/pecl82 /usr/bin/pecl
RUN ln -s /usr/bin/php82 /usr/bin/php

RUN \
    pecl update-channels && \
    rm -rf /tmp/pear ~/.pearrc

RUN adduser -u 82 -D -S -G www-data www-data
RUN install -d -m 0777 -o www-data -g www-data /var/www/html

RUN \
    wget -O /usr/local/bin/phpunit https://phar.phpunit.de/phpunit-9.phar && chmod 0755 /usr/local/bin/phpunit && \
    wget -O /usr/local/bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod 0755 /usr/local/bin/wp && \
    wget -q https://getcomposer.org/installer -O - | php -- --install-dir=/usr/bin/ --filename=composer

ENV WP_CLI_CONFIG_PATH /config/wp-cli.yaml
ENV PHP_INI_DIR /etc/php82

COPY rootfs-common/ /
COPY rootfs82/ /
COPY --from=build /usr/lib/php82/modules/memcache.so /usr/lib/php82/modules/gmagick.so /usr/lib/php82/modules/

WORKDIR /var/www/html
STOPSIGNAL SIGQUIT
EXPOSE 9000
ENTRYPOINT ["docker-php-entrypoint"]
CMD ["run.sh"]
