FROM ghcr.io/automattic/vip-container-images/alpine:3.19.0@sha256:ba68ecabb1fbe577d6b5fdf86c37ac62387d7325ec7aafbe15b3f0e17905b484

COPY setup.sh add-site.sh dev-env-plugin.php wp-config* /dev-tools/
COPY scripts /scripts

CMD ["sleep", "infinity"]
