FROM ghcr.io/automattic/vip-container-images/alpine:3.17.2@sha256:d0d035a71e27df5abee64bb9254632bb63a6dd3e03dbc16bcaca680519d607bd

COPY setup.sh add-site.sh dev-env-plugin.php wp-config* /dev-tools/
COPY scripts /scripts

CMD ["sleep", "infinity"]
