FROM ghcr.io/automattic/vip-container-images/alpine:3.19.0@sha256:1a3f8755404f7f8dd05ac461f6026dd442b383400cf676888d8ba7ff0bcfa682

COPY setup.sh add-site.sh dev-env-plugin.php wp-config* /dev-tools/
COPY scripts /scripts

CMD ["sleep", "infinity"]
