name: Build Docker image
description: Builds a Docker image
inputs:
  context:
    description: The directory containing the Dockerfile
    required: true
  file:
    description: The Dockerfile to use
    required: false
  platforms:
    description: The platforms to build for
    required: false
    default: linux/amd64,linux/arm64
  push:
    description: Whether to push the image to the registry
    required: true
  primaryTag:
    description: The primary tag to use for the image
    required: true
  tags:
    description: The tags to use for the image
    required: false
  args:
    description: List of build-time variables
    required: false
  cache-from:
    description: List of external cache sources for buildx
    required: false
  cache-to:
    description: List of cache export destinations for buildx
    required: false
  no-cache:
    description: Do not use cache when building the image
    required: false
    default: 'false'
  registry:
    description: The registry to use
    required: false
    default: https://ghcr.io
  username:
    description: The username to use for the registry
    required: false
    default: ${{ github.actor }}
  password:
    description: The password to use for the registry
    required: false
    default: ${{ github.token }}
  auth_token:
    description: The token to authenticate with GitHub
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build and push container image
      uses: docker/build-push-action@v6
      id: push
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push }}
        sbom: true
        tags: |
          ${{ inputs.primaryTag }}
          ${{ inputs.tags }}
        build-args: ${{ inputs.args }}
        cache-from: ${{ inputs.cache-from }}
        cache-to: ${{ inputs.cache-to }}
        no-cache: ${{ inputs.no-cache }}

    - name: Get image name
      shell: bash
      id: imagename
      run: echo "image_name=$(echo "${{ inputs.primaryTag }}" | cut -d ':' -f 1)" >> "${GITHUB_OUTPUT}"

    - name: Generate SBOM
      uses: anchore/sbom-action@61119d458adab75f756bc0b9e4bde25725f86a7a # v0.17.2
      with:
        image: ${{ inputs.primaryTag }}
        format: 'cyclonedx-json'
        output-file: 'sbom.cyclonedx.json'
      if: inputs.push == 'true'

    - name: Attest SBOM
      uses: actions/attest-sbom@5026d3663739160db546203eeaffa6aa1c51a4d6 # v1.4.1
      with:
        subject-name: ${{ steps.imagename.outputs.image_name }}
        subject-digest: ${{ steps.push.outputs.digest }}
        sbom-path: 'sbom.cyclonedx.json'
        push-to-registry: true
      if: inputs.push == 'true'

    - name: Attest provenance
      uses: actions/attest-build-provenance@1c608d11d69870c2092266b3f9a6f3abbf17002c # v1.4.3
      with:
        subject-name: ${{ steps.imagename.outputs.image_name }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
      if: inputs.push == 'true'

    - name: Load image to local Docker
      uses: docker/build-push-action@v6
      with:
        load: true
        push: false
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        tags: |
          ${{ inputs.primaryTag }}
          ${{ inputs.tags }}
        build-args: ${{ inputs.args }}

    - name: Generate filename for SARIF
      shell: bash
      id: filename
      run: |
        echo "filename=trivy-$(basename "${{ inputs.primaryTag }}" | tr '\\/:' '-').sarif" >> "${GITHUB_OUTPUT}"

    - name: Create cache directory
      shell: bash
      run: mkdir -p .cache/trivy/db

    - name: Restore Trivy database
      uses: actions/cache/restore@v4.1.1
      with:
        path: .cache/trivy/db
        key: trivy

    - name: Calculate database hash
      shell: bash
      id: old_hash
      run: |
        if [ -f .cache/trivy/db/trivy.db ]; then
          echo "hash=$(sha256sum -b .cache/trivy/db/trivy.db | awk '{print $1}')" >> "${GITHUB_OUTPUT}"
        else
          echo "hash=" >> "${GITHUB_OUTPUT}"
        fi

    - name: Security Scan
      shell: bash
      run: |
        docker run --rm \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v $(pwd)/.cache:/root/.cache \
          -v $(pwd):/workdir \
          -w /workdir \
          aquasec/trivy:0.56.1 image --format json --ignore-unfixed --pkg-types os --scanners vuln --db-repository ghcr.io/aquasecurity/trivy-db:2,public.ecr.aws/aquasecurity/trivy-db:2 ${{ inputs.primaryTag }} --output trivy.json
        sudo chmod a+r -R .cache

    - name: Calculate database hash
      shell: bash
      id: new_hash
      run: |
        if [ -f .cache/trivy/db/trivy.db ]; then
          echo "hash=$(sha256sum -b .cache/trivy/db/trivy.db | awk '{print $1}')" >> "${GITHUB_OUTPUT}"
        else
          echo "hash=" >> "${GITHUB_OUTPUT}"
        fi

    - name: Cache Trivy database
      uses: actions/cache/save@v4.1.1
      with:
        path: .cache/trivy/db
        key: trivy
      if: steps.old_hash.outputs.hash != steps.new_hash.outputs.hash && steps.new_hash.outputs.hash != ''

    - name: Print report
      uses: docker://aquasec/trivy:0.56.1
      with:
        args: convert --format=table trivy.json

    - name: Generate SARIF
      uses: docker://aquasec/trivy:0.56.1
      with:
        args: convert --format=sarif --output=${{ steps.filename.outputs.filename }} trivy.json
      if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name

    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@v3.26.11
      with:
        sarif_file: ${{ steps.filename.outputs.filename }}
      if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
      continue-on-error: true

    - name: Prepare markdown report
      uses: docker://aquasec/trivy:0.56.1
      with:
        args: convert --format=template --template=@.github/actions/build-docker-image/markdown.tpl --output=trivy.md trivy.json
      if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name

    - name: Find Trivy Scan Report comment
      uses: peter-evans/find-comment@v3
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body-includes: ${{ inputs.primaryTag }}
      if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name

    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body-path: trivy.md
        edit-mode: replace
      if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
