name: Build Alpine

on:
  push:
    branches:
      - master
    paths:
      - "alpine/**"
      - ".github/workflows/alpine.yml"
  pull_request:
    paths:
      - "alpine/**"
      - ".github/workflows/alpine.yml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      deployments: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get image version
        id: getversion
        run: echo "version=$(head -n 1 alpine/Dockerfile | sed -e 's/FROM alpine:\(.*\)/\1/')" >> $GITHUB_OUTPUT

      - name: Start Deployment
        uses: bobheadxi/deployments@v1.4.0
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: alpine-latest

      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          file: alpine/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.base_ref == null }}
          cache-from: type=gha,scope=alpine
          cache-to: type=gha,mode=max,scope=alpine
          tags: |
            ghcr.io/${{ github.repository }}/alpine:latest
            ghcr.io/${{ github.repository }}/alpine:${{ steps.getversion.outputs.version }}

      - name: Update Deployment
        uses: bobheadxi/deployments@v1.4.0
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env: ${{ steps.deployment.outputs.env }}
          env_url: https://ghcr.io/${{ github.repository }}/alpine:latest
