name: Build Alpine

on:
  push:
    branches:
      - master
    paths:
      - "alpine/**"
      - ".github/workflows/alpine.yml"
  pull_request:
    paths:
      - "alpine/**"
      - ".github/workflows/alpine.yml"

permissions:
  contents: read

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@3df53dd32d858478710a6127bcd8b9d8b7182e16 # tag=v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480 # tag=v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25 # tag=v1
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # tag=v1
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get image version
        id: getversion
        run: echo "::set-output name=version::$(head -n 1 alpine/Dockerfile | sed -e 's/FROM alpine:\(.*\)/\1/')"
      - name: Build container image
        uses: docker/build-push-action@1814d3dfb36d6f84174e61f4a4b05bd84089a4b9 # tag=v2
        with:
          file: alpine/Dockerfile
          platforms: linux/amd64,linux/arm64
          # base_ref is only defined in PRs, hence we're only pushing when we're not in a PR
          push: ${{ github.base_ref == null }}
          tags: |
            ghcr.io/automattic/vip-container-images/alpine:latest
            ghcr.io/automattic/vip-container-images/alpine:${{ steps.getversion.outputs.version }}
