name: Build MariaDB Lite Image

on:
  push:
    branches:
      - master
    paths:
      - "mariadb-lite/**"
      - ".github/workflows/mariadb-lite.yml"
  pull_request:
    branches:
      - master
    paths:
      - "mariadb-lite/**"
      - ".github/workflows/mariadb-lite.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the source code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Login to DockerHub
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # tag=v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name != 'pull_request' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # tag=v2.0.0

      - name: Get image version
        id: getversion
        run: |
          echo "::set-output name=version::$(awk -F: '/^FROM / {print gensub(/\@.+/, "", "g", $2)}' mariadb-lite/Dockerfile)"

      - name: Build and push
        uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8 # tag=v3.0.0
        with:
          context: mariadb-lite
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/automattic/vip-container-images/mariadb-lite:${{ steps.getversion.outputs.version }}
