name: Build MariaDB Lite Image

on:
  push:
    branches:
      - master
    paths:
      - "mariadb-lite/**"
      - ".github/workflows/mariadb-lite.yml"
  pull_request:
    branches:
      - master
    paths:
      - "mariadb-lite/**"
      - ".github/workflows/mariadb-lite.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the source code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name != 'pull_request' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get image version
        id: getversion
        run: |
          echo "version=$(awk -F: '/^FROM / {print gensub(/@.+/, "", "g", $2)}' mariadb-lite/Dockerfile)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: mariadb-lite
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha,scope=mariadb-lite
          cache-to: type=gha,mode=max,scope=mariadb-lite
          tags: |
            ghcr.io/automattic/vip-container-images/mariadb-lite:${{ steps.getversion.outputs.version }}
