name: Build MariaDB Lite Image

on:
  push:
    branches:
      - master
    paths:
      - "mariadb-lite/**"
      - ".github/workflows/mariadb-lite.yml"
  pull_request:
    branches:
      - master
    paths:
      - "mariadb-lite/**"
      - ".github/workflows/mariadb-lite.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the source code
        uses: actions/checkout@3df53dd32d858478710a6127bcd8b9d8b7182e16 # tag=v3

      - name: Login to DockerHub
        uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7 # tag=v1
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name != 'pull_request' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25 # tag=v1.6.0

      - name: Get image version
        id: getversion
        run: |
          echo "::set-output name=version::$(awk -F: '/^FROM / {print $2}' mariadb-lite/Dockerfile)"

      - name: Build and push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a # tag=v2.7.0
        with:
          context: mariadb-lite
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/automattic/vip-container-images/mariadb-lite:${{ steps.getversion.outputs.version }}
