name: Build MariaDB Lite Image

on:
  push:
    branches:
      - master
    paths:
      - "mariadb-lite/**"
      - ".github/workflows/mariadb-lite.yml"
  pull_request:
    branches:
      - master
    paths:
      - "mariadb-lite/**"
      - ".github/workflows/mariadb-lite.yml"
  workflow_dispatch:

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name != 'pull_request' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Get image version
        id: getversion
        run: |
          echo "::set-output name=version::$(awk -F: '/^FROM / {print $2}' mariadb-lite/Dockerfile)"

      - name: Build and push
        uses: docker/build-push-action@v2.7.0
        with:
          context: mariadb-lite
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/automattic/vip-container-images/mariadb-lite:${{ steps.getversion.outputs.version }}
