name: Build MU Plugins

on:
  push:
    branches:
      - master
    paths:
      - "mu-plugins-wpc/**"
      - ".github/workflows/mu-plugins-wpc.yml"
  pull_request:
    paths:
      - "mu-plugins-wpc/**"
      - ".github/workflows/mu-plugins-wpc.yml"
  workflow_dispatch:
  repository_dispatch:
    types:
      - build-mu-plugins-wpc

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the source code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@b60f85385d03ac8acfca6d9996982511d8620a19 # v4.3.0
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Login to DockerHub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name != 'pull_request' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Build and push
        uses: docker/bake-action@37816e747588cb137173af99ab33873600c46ea8 # v6.8.0
        with:
          source: .
          workdir: mu-plugins-wpc
          files: docker-bake.hcl
          push: ${{ github.event_name != 'pull_request' }}
          no-cache: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || github.event_name == 'repository_dispatch' }}
          set: |
            *.output=type=docker,rewrite-timestamp=true
            *.output=type=image,push=${{ github.base_ref == null }},rewrite-timestamp=true
        env:
          SOURCE_DATE_EPOCH: 0
          GITHUB_TOKEN: ${{ github.token }}
