name: Build Nginx

on:
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get image version
        id: getversion
        run: echo "::set-output name=version::$(head -n 1 nginx/Dockerfile | sed -e 's/FROM nginx:\(.*\)-alpine/\1/')"
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          file: nginx/Dockerfile
          platforms: linux/amd64,linux/arm64
          # base_ref is only defined in PRs, hence we're only pushing when we're not in a PR
          push: ${{ github.base_ref == null }}
          tags: |
            ghcr.io/automattic/vip-container-images/nginx:latest
            ghcr.io/automattic/vip-container-images/nginx:${{ steps.getversion.outputs.version }}
