name: Build Alternative PHP-FPM

on:
  push:
    branches:
      - master
    paths:
      - "php-fpm-alt/**"
      - ".github/workflows/php-fpm-alt.yml"
  pull_request:
    paths:
      - "php-fpm-alt/**"
      - ".github/workflows/php-fpm-alt.yml"

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages (PHP ${{ matrix.php.name }})
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        php:
          - name: "7.4"
            suffix: "74"
          - name: "8.0"
            suffix: "80"
          - name: "8.1"
            suffix: "81"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f211e3e9ded2d9377c8cadc4489a4e38014bc4c9
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: php-fpm-alt
          platforms: linux/amd64,linux/arm64
          file: php-fpm-alt/Dockerfile.${{ matrix.php.suffix }}
          push: ${{ github.base_ref == null }}
          pull: true
          cache-from: type=gha,scope=php-fpm-alt-${{ matrix.php.suffix }}
          cache-to: type=gha,mode=max,scope=php-fpm-alt-${{ matrix.php.suffix }}
          tags: ghcr.io/automattic/vip-container-images/php-fpm-alt:${{ matrix.php.name }}
