name: Build PHP-FPM

on:
  push:
    branches:
      - master
    paths:
      - "php-fpm/**"
      - ".github/workflows/php-fpm.yml"
  pull_request:
    paths:
      - "php-fpm/**"
      - ".github/workflows/php-fpm.yml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages (PHP ${{ matrix.php.name }})
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        php:
          - name: "7.4"
            suffix: "74"
          - name: "8.0"
            suffix: "80"
          - name: "8.1"
            suffix: "81"
    steps:
      - name: Check out the repo
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8 # tag=v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # tag=v2.0.0
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # tag=v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5 # tag=v3
        with:
          context: php-fpm
          platforms: linux/amd64,linux/arm64
          file: php-fpm/Dockerfile.${{ matrix.php.suffix }}
          push: ${{ github.base_ref == null }}
          pull: true
          cache-from: type=gha,scope=php-fpm-${{ matrix.php.suffix }}
          cache-to: type=gha,mode=max,scope=php-fpm-${{ matrix.php.suffix }}
          tags: ghcr.io/automattic/vip-container-images/php-fpm-alt:${{ matrix.php.name }}, ghcr.io/automattic/vip-container-images/php-fpm:${{ matrix.php.name }}
