name: Build PHP-FPM

on:
  push:
    branches:
      - master
    paths:
      - "php-fpm/**"
      - ".github/workflows/php-fpm.yml"
  pull_request:
    paths:
      - "php-fpm/**"
      - ".github/workflows/php-fpm.yml"

permissions:
  contents: read

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@3df53dd32d858478710a6127bcd8b9d8b7182e16 # tag=v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480 # tag=v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f211e3e9ded2d9377c8cadc4489a4e38014bc4c9 # tag=v1.7.0
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # tag=v1
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get image version
        id: getversion
        run: echo "::set-output name=version::$(head -n 1 php-fpm/Dockerfile | sed -e 's/FROM php:\(.*\)-fpm-alpine3.14/\1/')"
      - name: Build container image
        uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8 # tag=v2
        with:
          context: php-fpm
          platforms: linux/amd64,linux/arm64
          # base_ref is only defined in PRs, hence we're only pushing when we're not in a PR
          push: ${{ github.base_ref == null }}
          pull: true
          cache-from: type=gha,scope=php-fpm
          cache-to: type=gha,mode=max,scope=php-fpm
          tags: |
            ghcr.io/automattic/vip-container-images/php-fpm:latest
            ghcr.io/automattic/vip-container-images/php-fpm:${{ steps.getversion.outputs.version }}
