name: Build PHP-FPM

on:
  push:
    branches:
      - master
    paths:
      - "php-fpm/**"
      - ".github/workflows/php-fpm.yml"
  pull_request:
    paths:
      - "php-fpm/**"
      - ".github/workflows/php-fpm.yml"

permissions:
  contents: read

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8 # tag=v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # tag=v2.0.0
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # tag=v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get image version
        id: getversion
        run: echo "::set-output name=version::$(head -n 1 php-fpm/Dockerfile | sed -re 's/FROM php:([0-9]+\.[0-9]+)-.*$/\1/')"
      - name: Build container image
        uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8 # tag=v3
        with:
          context: php-fpm
          platforms: linux/amd64,linux/arm64
          # base_ref is only defined in PRs, hence we're only pushing when we're not in a PR
          push: ${{ github.base_ref == null }}
          pull: true
          cache-from: type=gha,scope=php-fpm
          cache-to: type=gha,mode=max,scope=php-fpm
          tags: |
            ghcr.io/automattic/vip-container-images/php-fpm:latest
            ghcr.io/automattic/vip-container-images/php-fpm:${{ steps.getversion.outputs.version }}
