name: Build PHP-FPM (Ubuntu)

on:
  push:
    branches:
      - master
    paths:
      - "php-fpm-ubuntu/**"
      - ".github/workflows/php-fpm-ubuntu.yml"
  pull_request:
    paths:
      - "php-fpm-ubuntu/**"
      - ".github/workflows/php-fpm-ubuntu.yml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages (PHP ${{ matrix.php.name }})
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      deployments: write
    strategy:
      fail-fast: false
      matrix:
        php:
          - name: "7.4"
            suffix: "74"
          - name: "8.0"
            suffix: "80"
          - name: "8.1"
            suffix: "81"
          - name: "8.2"
            suffix: "82"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Start Deployment
        uses: bobheadxi/deployments@v1.4.0
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: php-fpm-ubuntu-${{ matrix.php.name }}

      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          context: php-fpm-ubuntu
          platforms: linux/amd64,linux/arm64
          file: php-fpm-ubuntu/Dockerfile.${{ matrix.php.suffix }}
          push: ${{ github.base_ref == null }}
          pull: true
          cache-from: type=gha,scope=php-fpm-ubuntu-${{ matrix.php.suffix }}
          cache-to: type=gha,mode=max,scope=php-fpm-ubuntu-${{ matrix.php.suffix }}
          tags: ghcr.io/${{ github.repository }}/php-fpm-ubuntu:${{ matrix.php.name }}

      - name: Update Deployment
        uses: bobheadxi/deployments@v1.4.0
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env: ${{ steps.deployment.outputs.env }}
          env_url: https://ghcr.io/${{ github.repository }}/php-fpm-ubuntu:${{ matrix.php.name }}
