name: Build PHP-FPM

on:
  push:
    branches:
      - master
    paths:
      - "php-fpm/**"
      - ".github/workflows/php-fpm.yml"
      - ".github/actions/build-docker-image/**"
  pull_request:
    paths:
      - "php-fpm/**"
      - ".github/workflows/php-fpm.yml"
      - ".github/actions/build-docker-image/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages (PHP ${{ matrix.php.name }})
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      pull-requests: write
      security-events: write
      id-token: write
      attestations: write
    strategy:
      fail-fast: false
      matrix:
        php:
          - name: "8.1"
            suffix: "81"
          - name: "8.2"
            suffix: "82"
          - name: "8.3"
            suffix: "83"
          - name: "8.4"
            suffix: "84"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Build and push image
        uses: ./.github/actions/build-docker-image
        with:
          context: php-fpm
          file: php-fpm/Dockerfile.${{ matrix.php.suffix }}
          push: ${{ github.base_ref == null }}
          no-cache: ${{ github.event_name == 'workflow_dispatch' }}
          cache-from: type=gha,scope=php-fpm-${{ matrix.php.suffix }}
          cache-to: type=gha,mode=max,scope=php-fpm-${{ matrix.php.suffix }}
          primaryTag: ghcr.io/automattic/vip-container-images/php-fpm:${{ matrix.php.name }}
          tags: ghcr.io/automattic/vip-container-images/php-fpm-alt:${{ matrix.php.name }}
