name: Build PHP Helpers image

on:
  push:
    branches:
      - master
    paths:
      - "php-helpers/**"
      - ".github/workflows/php-helpers.yml"
  pull_request:
    branches:
      - master
    paths:
      - "php-helpers/**"
      - ".github/workflows/php-helpers.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the source code
        uses: actions/checkout@v6

      - name: Set up Docker
        uses: docker/setup-docker-action@b2189fbf2a6592b51fee7cdd93ee2bfaeba733db # v5.1.0
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Login to DockerHub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name != 'pull_request' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Build and push
        uses: docker/bake-action@6614cfa25eff9a0b2b2697efb0b6159e7680d584 # v7.2.0
        with:
          source: php-helpers
          files: docker-bake.hcl
          push: ${{ github.event_name != 'pull_request' }}
          no-cache: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
          set: |
            *.output=type=docker,rewrite-timestamp=true
            *.output=type=image,push=${{ github.base_ref == null }},rewrite-timestamp=true,name=ghcr.io/automattic/vip-container-images/php-helpers:latest
        env:
          SOURCE_DATE_EPOCH: 0
