name: Build Statsd

on:
  push:
    branches:
      - master
    paths:
      - "statsd/**"
      - ".github/workflows/statsd.yml"
  pull_request:
    paths:
      - "statsd/**"
      - ".github/workflows/statsd.yml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get image version
        id: getversion
        run: |
          echo "version=$(awk -F: '/^FROM / {print gensub(/\@.+/, "", "g", $2)}' statsd/Dockerfile)" >> $GITHUB_OUTPUT

      - name: Build container image
        uses: docker/build-push-action@v3
        with:
          context: statsd
          platforms: linux/amd64,linux/arm64
          push: ${{ github.base_ref == null }}
          cache-from: type=gha,scope=statsd
          cache-to: type=gha,mode=max,scope=statsd
          tags: |
            ghcr.io/automattic/vip-container-images/statsd:latest
            ghcr.io/automattic/vip-container-images/statsd:${{ steps.getversion.outputs.version }}
