name: Build traefik3 with OpenSSL

on:
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      pull-requests: write
      security-events: write
      id-token: write
      attestations: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get image version
        id: getversion
        run: echo "version=$(head -n 1 traefik3/Dockerfile | sed -r -e 's/^([^:]+):([^ @$-]+).*/\2/')" >> "${GITHUB_OUTPUT}"

      - name: Build and push image
        uses: ./.github/actions/build-docker-image
        with:
          context: traefik3
          push: true
          cache-from: type=gha,scope=traefik3
          cache-to: type=gha,mode=max,scope=traefik3
          primaryTag: ghcr.io/automattic/vip-container-images/traefik3_openssl:${{ steps.getversion.outputs.version }}
          tags: ghcr.io/automattic/vip-container-images/traefik3_openssl:latest
