name: Build WordPress

on:
  push:
    branches:
      - master
    paths:
      - "wordpress/**"
      - ".github/workflows/wordpress.yml"
  pull_request:
    paths:
      - "wordpress/**"
      - ".github/workflows/wordpress.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare build matrix
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      - name: Read versions.json
        id: set-matrix
        run: |
          jq -c '.' versions.json
          echo "::set-output name=matrix::$(jq -c '.' versions.json)"
        working-directory: wordpress
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  build:
    name: "Build Docker image (ref: ${{ matrix.wp.ref }}, tag: ${{ matrix.wp.tag }})"
    runs-on: ubuntu-latest
    needs: prepare
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        wp: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - name: Check out source code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      - name: Set additional tags
        id: extra-tags
        run: |
          if [ "${{ matrix.wp.locked }}" = "true" ]; then
            echo "::set-output name=tags::ghcr.io/automattic/vip-container-images/wordpress:${{ matrix.wp.tag }}-locked"
          else
            echo "::set-output name=tags::"
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8 # tag=v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # tag=v2.0.0

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # tag=v2
        if: ${{ github.base_ref == null }}
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build WordPress image
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94 # tag=v3
        with:
          platforms: linux/amd64,linux/arm64
          context: wordpress
          push: ${{ github.base_ref == null }}
          build-args: WP_GIT_REF=${{ matrix.wp.ref }}
          cache-from: type=gha,scope=wordpress-${{ matrix.wp.ref }}
          cache-to: type=gha,mode=max,scope=wordpress-${{ matrix.wp.ref }}
          no-cache: ${{ matrix.wp.cacheable == false }}
          tags: |
            ghcr.io/automattic/vip-container-images/wordpress:${{ matrix.wp.tag }}
            ${{ steps.extra-tags.outputs.tags }}
