name: Build WordPress from master (nightly) branch

on:
  schedule:
    - cron:  '0 15 * * *'

jobs:
  push_to_registry:
    name: Push images to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull latest master WordPress
        run: 
          git subtree pull -P wordpress/public/master https://github.com/WordPress/WordPress master --squash -m "Updating WordPress master"
          git push
      - name: Build nightly container image
        uses: docker/build-push-action@v2
        with:
          file: wordpress/Dockerfile
          platforms: linux/amd64,linux/arm64
          context: wordpress/public/master
          push: true
          tags: |
            ghcr.io/automattic/vip-container-images/wordpress:master
