name: Build WordPress Tests Library

on:
  push:
    branches:
      - master
    paths:
      - "wordpress-tests-library/**"
      - ".github/workflows/wordpress-tests-library.yml"
      - ".github/actions/build-docker-image/**"
  pull_request:
    paths:
      - "wordpress-tests-library/**"
      - ".github/workflows/wordpress-tests-library.yml"
      - ".github/actions/build-docker-image/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build images"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write
      security-events: write
      id-token: write
      attestations: write
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@370a7dad4b8ce8dbf00f9363e1652e5074dd6abe # v4.1.0
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Generate wordpress.json
        run: |
          jq '{ WORDPRESS_VERSIONS: . }' ../wordpress/versions.json > wordpress.json
        working-directory: wordpress-tests-library

      - name: Build and push
        uses: docker/bake-action@v6
        with:
          source: .
          workdir: wordpress-tests-library
          files: variables.hcl,docker-bake.hcl,wordpress.json
          push: ${{ github.base_ref == null }}
          set: |
            *.platform=linux/amd64,linux/arm64
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
            *.output=type=docker,rewrite-timestamp=true
            *.output=type=image,push=${{ github.base_ref == null }},rewrite-timestamp=true
        env:
          SOURCE_DATE_EPOCH: 0
