name: Build WP Core Test Runner image

on:
  push:
    branches:
      - master
    paths:
      - "wp-core-test-runner/**"
      - ".github/workflows/wp-core-test-runner.yml"
  pull_request:
    branches:
      - master
    paths:
      - "wp-core-test-runner/**"
      - ".github/workflows/wp-core-test-runner.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the source code
        uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2

      - name: Login to DockerHub
        uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7 # v1
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name != 'pull_request' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25 # v1.6.0

      - name: Set up Docker Metadata
        id: meta
        uses: docker/metadata-action@e5622373a38e60fb6d795a4421e56882f2d7a681 # v3.6.2
        with:
          images: ghcr.io/automattic/vip-container-images/wp-core-test-runner
          tags: |
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229 # v2.7.0
        with:
          context: wp-core-test-runner
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
