name: Build WP Core Test Runner image

on:
  push:
    branches:
      - master
    paths:
      - "wp-core-test-runner/**"
      - ".github/workflows/wp-core-test-runner.yml"
  pull_request:
    branches:
      - master
    paths:
      - "wp-core-test-runner/**"
      - ".github/workflows/wp-core-test-runner.yml"
  workflow_dispatch:
  schedule:
    - cron: "46 15 * * *"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the source code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      - name: Login to DockerHub
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # tag=v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name != 'pull_request' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # tag=v2.0.0

      - name: Set up Docker Metadata
        id: meta
        uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a # tag=v4.0.1
        with:
          images: ghcr.io/automattic/vip-container-images/wp-core-test-runner
          tags: |
            type=raw,value=latest

      # Keep in sync with Dockerfile
      - name: Get the list of WordPress versions
        id: versions
        run: |
          echo ::set-output name=versions::$(wget https://api.wordpress.org/core/version-check/1.7/ -q -O - | jq -r '[.offers[].version] | unique | map(select( . >= "5.9")) | .[]' | xargs echo)

      - name: Build and push
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94 # tag=v3
        with:
          context: wp-core-test-runner
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: CACHE_BUSTER=${{ steps.versions.outputs.versions }}
          cache-from: type=gha,scope=wp-core-test-runner
          cache-to: type=gha,mode=max,scope=wp-core-test-runner
